name: build nugets
on:
  workflow_dispatch:
  inputs:
      publishEnabled:
        description: "Publish to Nuget.org"
        type: boolean
        required: false
        default: false

jobs:
  build_and_publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: "6.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Generate NuGet packages
        id: build_nugets
        run: powershell ./Generate-NuGets.ps1 -revision ${{  github.run_number  }} -outputfolder nupkgs

      - name: Publish NuGet
        if: ${{ success() && github.event.inputs.publishEnabled == 'true' }}
        env:
          token: ${{secrets.EVERGINE_NUGETORG_TOKEN}}
        run: |
          cd ${{  env.nugetOutputPath  }}
          ls *.nupkg
          dotnet nuget push "nupkgs/*.nupkg" --skip-duplicate --no-symbols -k "$env:token" -s https://api.nuget.org/v3/index.json